@startuml

class Position{
- x: int
- y: int
+ Position(int, int)
+ getX(): int
+ getY(): int
+ setX(int)
+ setY(int)
}

Position <-- Monstre : appartient

class Monstre{
+ Monstre(int, int)

}

Position <-- Perso : appartient

class Perso{
+ Perso(int, int)
+ etrePresent (int, int)
}

Monstre "*" <-- "1" Labyrinthe : appartient
Perso "*" <-- "1" Labyrinthe : appartient

class Labyrinthe{
- pj: Perso
- monstre: Monstre
- murs: boolean[][]
+ getSuivant(int, int, String)
+ Labyrinthe(String)
+ ajoutMonstreLaby()
+ getMonstre()
+ deplacerPerso(String)
+ deplacerAleatoire()
+ etreFini(): boolean
+ getLengthY(): int
+ getLength(): int
+ getMur(int x, int y): boolean
+ getPerso(): Perso
}

@enduml