@startuml
hide footbox

participant "labyJ : LabyJeu" as lj
participant "lab : Labyrinthe" as l
participant "m : Monstre" as m
participant "e : Entite" as e

    activate lj
    lj -> l : deplacerMonstre()
    activate l
    l -> m : deplacer(lab)
    activate m

    m -> l : peutSeDeplacer()
    activate l
    l --> m : true
    deactivate l

    m -> e : setX()
    m -> e : setY()
    m --> l
    deactivate m
    l --> lj
    deactivate l
    deactivate lj

note across
Le LabyJeu appelle la methode deplacerMonstre() du Labyrinthe.
Cette methode appelle elle-meme la methode deplacer(lab) de Monstre
qui teste si le monstre peut se deplacer ou non (avec la methode)
peutSeDeplacer() de Labyrinthe. Si le monstre peut se deplacer, alors
les coordonnees du monstre sont changees grace aux setters de son
parent Entite. Le monstre est alors deplace.
end note

@enduml