@startuml
hide footbox

title Deplacer le Personnage

participant "Clavier" as c
participant "lab: Labyrinthe" as l
participant "p: Perso" as p
participant "e: Entite" as e


c -> l : deplacerPerso(String)
activate l
    l -> p : deplacer()
    activate p
        p -> l : peutSeDeplacer()
        activate l
            l --> p : true
        deactivate l
        p -> e : setX()
        activate e
         p -> e : setY()
    deactivate p
    e --> l
    deactivate e
    l--> c
deactivate l

note across
En fonction de la touche pressee, le Clavier appelle
la methode deplacerPerso() de Labyrinthe qui elle-meme
appelle la methode deplacer() de Perso. Afin de savoir si
le personnage peut se deplacer, la classe Perso utilise
la methode peutSeDeplacer du Labyrinthe qui renvoie true
si le personnage peut se deplacer. Dans ce cas, la classe
Personnage attribue de nouvelles coordonnees au heros en
utilisant les setters de son parent Entite. Le personnage a
donc bien ete deplace.
end note

@enduml