@startuml

class Position{
- x: int
- y:  int
+ Position(int, int)
+ getX(): int
+ getY(): int
+ setX(int)
+ setY(int)
}

Position <-- Monstre : appartient

class Monstre{
+ Monstre(int, int)
+ deplacerAleatoire()
}

Position <-- Personnage : appartient

class Personnage{
+ Personnage(int, int)
}

Monstre "*" <-- "1" Labyrinthe : appartient
Personnage "*" <-- "1" Labyrinthe : appartient

class Labyrinthe{
}

@enduml