@startuml
hide footbox

participant "main" as m
participant "m: Monstre" as ms
participant "p: Perso" as p

m -> ms : attaquer(Perso p)
activate ms
ms -> p : subirDegats(int)
activate p
p --> ms
deactivate p
ms --> m
deactivate ms
@enduml