@startuml
hide footbox

participant "main" as m
participant "l: LabyJeu" as lj
participant "laby: Labyrinthe" as lb
participant "m: Monstre" as ms
m -> lj : update()
activate lj

lj -> lb : actionMonstre()
activate lb

lb -> ms : estProcheDePerso(Labyrinthe l)
activate ms
ms --> lb : false
deactivate ms


lb -> ms : deplacer(Labyrinthe l)
activate ms

ms --> lb
deactivate ms


lb --> lj
deactivate ms
deactivate lb

lj --> m
deactivate lj
@enduml