@startuml
hide footbox

participant "main" as m
participant "lab: Labyrinthe" as l
participant "ce: CaseEffet" as ce
participant "p: Perso" as p
participant "m: Monstre" as ms

create l
m -> l : new
activate l

  create ce
  l -> ce : new

  create p
  l -> p : new

  create ms
  l -> ms : new
  l --> m
deactivate l
@enduml