@startuml
hide footbox

title Mise à jour du jeu avec vérification des CaseEffet

participant "Main" as m
participant "jeu: LabyJeu" as j
participant "lab: Labyrinthe" as l
participant "entite: Entite" as e
participant "ce: CaseEffet" as ce

m -> j : update()
activate j
j -> l : etreCaseEffet(entite)
activate l
l -> ce : getEffet()
activate ce
ce --> l : effet
deactivate ce
l -> l : appliquerEffet(e, effet)
l -> e : getPv()
activate e
e --> l : pv
deactivate e
l -> e : setPv(pv)
l --> j : true
deactivate l

j --> m : void
deactivate j
@enduml