@startuml
hide footbox

participant "laby: Labyrinthe" as l
participant "labyDes: LabyDessin" as ld
participant "sp: Sprite" as s


activate ld
    l -> ld : dessinerJeu()
    activate s
        ld -> s : getImgSol()
        s --> ld : Image
        ld -> s : getImgHeros()
        s --> ld : Image
        ld -> s : getImgMonstre()
        s --> ld : Image
        ld -> s : getImgMonstreMort()
        s --> ld : Image
        ld -> s : getImgMur()
        s --> ld : Image
    deactivate s
    ld --> l
deactivate ld

note across
La classe Labyrinthe appelle la methode dessinerJeu de LabyDessin
qui elle-meme apppelle les getters (getImgSol, getImgHeros...) de la
classe Sprite qui renvoie donc les Images correspondantes au personnage,
au sol, aux monstres...
end note

@enduml